### PR TITLE
feat: support multiple endpoints

### PR DESCRIPTION
**Pull request by legendecas**
##### Checklist

- [x] `npm test` passes
- [x] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [x] commit message follows commit guidelines

##### Description of change

Add support for multiple grpc endpoint

Expect resolving https://github.com/eggjs/egg/issues/2466

### CODE REVIEW

**Comment by whxaxes** [comment]
ci is broken

**Comment by legendecas** [comment]
> ci is broken

CI is already broken on master branch. IMO it may be fixed in another PR. 🤓

**Comment by leoDreamer** [comment]
hello，when this PR will be merged

**Comment by atian25** [comment]
@whxaxes @thonatos 跟进下

**Comment by chapin666** [comment]
请问这个属性什么时候可以合并呢？

**Comment by leoDreamer** [comment]
@chapin666 自己合并发布了个 `egg-grpc-multiple-client` 先凑合用着吧，注意配置endpoints里，service 名用驼峰写

**Comment by chapin666** [comment]
@leoDreamer  不好意思，似乎有点问题
当调用其他节点grpc_server时，出现如下错误：
{ Grpc Error: 12 UNIMPLEMENTED: unknown service example.SmspcSubClass._invokeUnaryRequest (***********/node_modules/egg-grpc-multiple-client/lib/base_grpc.js:169:11)
    at GrpcSubClass._invokeRPC ***********/node_modules/egg-grpc-multiple-client/lib/base_grpc.js:116:17)
    at GrpcSubClass.BaseGrpc.(anonymous function) [as sendIdentifyingCode] (***********/node_modules/egg-grpc-multiple-client/lib/base_grpc.js:28:21)
...
 metadata: Metadata { _internal_repr: {} },
 details: 'unknown service example.Sms' }

**Comment by leoDreamer** [comment]
@chapin666 贴一下你proto文件和配置文件吧，应该是没有问题的，我这边是能正常使用的

**Comment by chapin666** [comment]
如下写法可以调用成功，但是将 package sms 修改成  package smss， ctx.grpc.sms.sms 修改成  ctx.grpc.smss.sms 后会失败。使用 egg-grpc 也会出现这个问题，可能是我配置不对。🙏。

###  sms.proto
```
syntax = "proto3";
package sms;
service Sms {
  rpc SendIdentifyingCode(IdentifyingCodeRequest) returns (IdentifyingCodeReply) {}
}
```

### config
```
exports.grpc = {
  endpoint: '10.254.65.12:65530',
};
```

### controller 
```
const client = ctx.grpc.sms.sms;
await client.sendIdentifyingCode({})
```

**Comment by leoDreamer** [comment]
@chapin666 
多客户端可以看看PR里的配置大概是：
```javascript
config.grpc = {
    endpoints: {
        'package.service': 'ip:port',
        'package.service': 'ip:port' // 使用驼峰命名
    }
}
```

**Comment by chapin666** [comment]
@leoDreamer  是我配置的问题。非常感谢。

**Comment by Jeff-Tian** [comment]
这个 PR 什么时候能合并呢？

**Comment by legendecas** [comment]
CI passed after cache disabled 🎉. The cache of the repo with node v8 has corrupted on travis.

**Comment by atian25** [comment]
@thonatos take a look

**Comment by zhaochy1990** [comment]
这个项目还在维护吗？

**Comment by legendecas** [comment]
Closing as I'm not interested in maintaining the patch list. Please feel free to pick it up if anyone is willing to do so.

**Pull request closed without merging**
